export const MOBILE_MAX_WIDTH = 520;

export const CHAPTER_TITLE_TOP_MARGIN_DESKTOP = 15;
export const CHAPTER_TITLE_TOP_MARGIN_MOBILE = 0;
export const CHAPTER_TITLE_BOTTOM_MARGIN_DESKTOP = 20;
export const CHAPTER_TITLE_BOTTOM_MARGIN_MOBILE = 20;
