name: Fly Deploy
on:
  push:
    branches:
      - production
      - develop
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create .env file
        run: |
          if [ "${{ github.ref }}" == "refs/heads/production" ]; then
            echo "ENV=production" > .env
          elif [ "${{ github.ref }}" == "refs/heads/develop" ]; then
            echo "ENV=development" > .env
          else
            echo "Unknown branch" > .env
          fi

      # - uses: erlef/setup-beam@v1
      #   with:
      #     otp-version: "26.0.2"
      #     gleam-version: "1.5.1"
      #     rebar3-version: "3"
      # - run: cd renderer_gleam && gleam deps download
      # - run: cd renderer_gleam && gleam run

      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: |
          if [ "${{ github.ref }}" == "refs/heads/production" ]; then
            flyctl deploy --remote-only --app little-bo-peep-solid 
          elif [ "${{ github.ref }}" == "refs/heads/develop" ]; then
            flyctl deploy --remote-only --app little-bo-peep-develop-solid
          else
            echo "Unknown branch, deployment skipped"
          fi
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
